#!/data/data/com.termux/files/usr/bin/python
import platform,os
os.system("git pull")
bit = platform.architecture()[0]
if bit == '64bit':
    import INSTAGRAM_HUB
elif bit == '32bit':
    import INSTAGRAM_HUB
    #print('\033[1;97m[✓] SORRY BRO YOUR DEVIS IS 32 BIT ')
 
